POST https://www.alpinresorts.com/api/offer/shop
Content-Type: application/json
Authorization: Bearer IA16S74Jm9llyseWWePfKGg1icGYIuWV7S30.XnDTQcDDjba8yO8ss8OwbN5wPQc9mKKH0MKL3PlV53cV5JHx4PjxTV9iM4DqkahATUod7mPP9gQn6qePtpFMmewgzFT2pcvX2OjzDyeamWYRUdQeIWnO7E1Sh3Zioz8DEgbCQ4SaFtcxUne6Iq4RTbr5gGgF9V3PW1bKmm75igQdAsieTaTSOZZnJRqeL8wLrF1gKo1.nE0b8RLbZlGUuCOFz9jqITOqagPTKNsFA2Gaw2aueSmpfJaR5amWu1W8xL57KOBqGMG6dVgi6QUd4VCIn7cFW4V2L23qqaK2KMb-hEVMoJKT3j6QMJw5vD-CU16kzG93B2yOL8eBCmeQ0O95TVEWhtE9EOFHl_Pry5HrrGJOwxWBo3ULUyfVmBjoyZUBwaHjlUWhWsmTYpey4WPi4GPtE1uAGdIHaNXVQC1ww8IGKkVPx7CIeTgBqglGM96yXBVWbSXsIPcxgmm57NOq08j1TqF2xYSr2FHIesJx6ZH3Pe8k-aJbBSSLiDQa1QvSRLTmtjSVG12hdIXVlgXixm2JJM5WmJiD5g2CnXJi6mWyySCO9snVFsrRfvx9AUt2iOcI6Gwf9fGOEPGG0i4N-OuG3UxT82vNHNURmW7BCjhQp7riHobJP5Fw2Ntco6TtEXxo8pjMk1L0wFmlucNup1eUz0JBOOdB7PBI5cFWpAD3YV2ZyHkjA00j_jX6cP6HNgWI2mJgoNNc2yhHZ15ADU9ks4RnmK5SvCgHGHm190NJvkYaEMUfgdIQPVFkgF9vAWWkSh2yQGaVJOpb1PjmlkVoWlb7-Ut8TNykunYX9rkx77KG7uAgskwA3wxdvQSMfCAqNnKBhEE4fZ7Rtq1TolsCJhUNvUkzXXcnfk9lBmszIvG

{
  "shopId": 136,
  "startDate": "2020-12-24",
  "endDate": "2020-12-31",
  "personAges": [
    6,
    23,
    42
  ],
  "offerType": "defaultProduct",
  "language": "en",
  "currency": "EUR"
}

###########################
### Sample Response
#HTTP/1.1 200 OK
#{
#  "id": "abcdefa9-71c1-4375-bf7b-dce8aef3cd49",
#  "total": 18392,
#  "shopId": 136,
#  "currency": "EUR",
#  "products": [
#    {
#      "productName": "Champion (5*) Ski",
#      "ageCategory": "child",
#      "price": 2584
#    },
#    {
#      "productName": "Red\/Silver (4*) Ski",
#      "ageCategory": "adult",
#      "price": 7904
#    },
#    {
#      "productName": "Red\/Silver (4*) Ski",
#      "ageCategory": "adult",
#      "price": 7904
#    }
#  ]
#}
###########################
